### ISSUE TITLE
[Bug][1.2.5] Setting stats to gold doesn't cause it to actually change until /reload

### ISSUE THREAD

**Issue by penguinsane** [failcoder/Supervillain_UI#130]
see title, also image: http://puu.sh/hTZwg/b993e367f4.jpg

**Comment by failcoder** [comment]
I believe this has been fixed.

**Comment by penguinsane** [comment]
Still not working. Specifically, I tried to change my System dock to Gold and it just doesn't wanna do it.
